### ISSUE TITLE
Solvation number

### ISSUE THREAD

**Issue by pelsa** [chemfiles/cfiles#10]
Why not adding an algorithm that computes the solvation number from the radial distribution function?

**Comment by Luthaf** [comment]
I think it is better to output the whole integral of the g(r) along with the g(r) output:

```
# r  g(r)  ∫g(r)
0     0      0
1     0      0
2     0      0
3     0      0
4     1      1
5     1      2
...
```

This way, people can use it as they want.

**Comment by Luthaf** [comment]
I pushed an implementation on the `rdf` branch. You can get the code for testing it on your data by running:
```
git clone https://github.com/chemfiles/cfiles
git checkout rdf
```

And then following the README instruction for compiling.

Other build options are documented [here](http://chemfiles.github.io/chemfiles/latest/installation.html#build-steps). You don't need this right now, but you may want to activate NetCDF support someday =)
