### ISSUE TITLE
Throw an error when no angles are found

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/cfiles#12]
Running `cfiles angle -s "..."` should return an error if no angles matching the selection were found, to allow the user to check for typos. Currently the code just continue and output NaN in the data file. 

We are already doing it for the [`rdf`](https://github.com/chemfiles/cfiles/blob/ea67cd7d202f5853392c2564b1b9024e56c95c82/src/commands/Rdf.cpp#L150-L154). Adding it for the angle should consist in adding the corresponding check in the [`Angle::accumulate`](https://github.com/chemfiles/cfiles/blob/ea67cd7d202f5853392c2564b1b9024e56c95c82/src/commands/Angles.cpp#L96) function.

I am willing to mentor anyone wanting to work on this. If you are interested, please comment here or on [gitter](https://gitter.im/chemfiles/chemfiles).

**Comment by lscalfi** [comment]
The selection could match angles in some frames and not others. We should check in the Angle::finish function.
