### ISSUE TITLE
Selections within selections

### ISSUE THREAD

**Issue by lscalfi** [chemfiles/cfiles#14]
It is for now possible to select atoms, bonds, angles or dihedrals on the base of their components' name, type, coordinates... 
It could be interesting to select atoms based on their bonded neighbours. We could create a selection inside a selection, for example: 
"atoms: name O and bonded to {name H and x<5}"
It could also be interesting to add a "water" selection.

**Comment by Luthaf** [comment]
As the selection capacities are provided by chemfiles, this issue should be in the main repo. 
Can you open it there? (https://github.com/chemfiles/chemfiles/issues/new)

Concerning the 'water' selection, this is tracked at https://github.com/chemfiles/chemfiles/issues/50
