### ISSUE TITLE
Segmentation fault if mismatched parentheses

### ISSUE THREAD

**Issue by lscalfi** [chemfiles/cfiles#27]
The command 
`cfiles angles ../nt12-24-full.trj.xyz --selection="angles: type(#1) Al and type(#2) O and type(#3) H )"`
gives a segmentation fault. (mismatched parentheses)

**Comment by Luthaf** [comment]
Ok, so this is actually a chemfiles problem, I can reproduce it with the following code:


```cpp
#include <chemfiles.hpp>

int main() {
    // This selection throw an error 
    // auto selection_1 = chemfiles::Selection("angles: type(#1) Al and type(#2) O )");
    // This selection segfault  
    auto selection_2 = chemfiles::Selection("angles: type(#1) Al and type(#2) O and type(#3) H )");
    return 0;
}
```

I am closing this in favor of https://github.com/chemfiles/chemfiles/issues/79
