### ISSUE TITLE
MSD gives wrong results

### ISSUE THREAD

**Issue by fxcoudert** [chemfiles/cfiles#40]
Take this XYZ trajectory: https://www.dropbox.com/s/5m4yxc2svbtuqcb/traj.xyz?dl=0

Calculating the MSD with:

```
cfiles msd traj.xyz  --guess-bonds --cell 19.383:19.383:19.383 --selection "name Se" -o Se-msd.dat
```

gives a MSD with a non-zero value near zero time:

![Capture d’écran 2020-01-09 à 14 32 59](https://user-images.githubusercontent.com/1980544/72071834-f6a68400-32ec-11ea-8fdf-058f888084db.png)

which is very unexpected. The trajectory appears OK to me.

**Comment by fxcoudert** [comment]
Surprisingly, trying to calculate the MSD in a non periodic system (without PBC) fails:

```
$ cfiles msd traj.xyz --selection "name Se" -o Se-msd.dat              
Error: can not unwrap in infinite unit cell
```

**Comment by Luthaf** [comment]
Thanks for the report!

I see what is wrong with the second non periodic case, but I don't know what is going on in the first graph. I'll look into it

**Comment by Luthaf** [comment]
Found the issues! I had got two normalization wrong, see https://github.com/chemfiles/cfiles/pull/41/commits/9f53cf95b7a39e6a239f0c5553f7c5aa5c1fff02.

I now get the following graph with your trajectory:
![se-msd](https://user-images.githubusercontent.com/6141587/72254883-99207900-3605-11ea-9423-35bea2d214b0.png)
which agree with the results generated with [tidynamics](http://lab.pdebuyl.be/tidynamics/) (thanks a lot @pdebuyl for this package, having it as a reference was great).

**Comment by fxcoudert** [comment]
Thanks @Luthaf !

**Comment by pdebuyl** [comment]
Thanks for the notification :-) I don't know much about users of the package, so it is nice to see it used.
