### ISSUE TITLE
 MSD giving wrong results with trajectory within NPT ensemble

### ISSUE THREAD

**Issue by like611** [chemfiles/cfiles#43]
Hi, the trajectory is in this link. (https://www.dropbox.com/s/lez3brm58lg13ya/1000K-NPT-200ps.gro?dl=0). The trajectory was obtained from classical MD within NPT ensemble for 200 ps at 1000 K.
Calculating MSD with this command:
`cfiles msd trj.gro --unwrap --selection "name O" -o O.dat`
the result was：
![1000K-NPT-C7 5-200ps](https://user-images.githubusercontent.com/45874475/105029086-d7f4d480-5a8c-11eb-8509-de738d6a4c5b.jpg)
which is abnormal that the MSD of oxygen atoms is higher than sodium atoms.
And if I kept the cell size constant, using this command:
`cfiles msd trj.xyz --unwrap --cell 16.03:16.03:16.03 --selection “name O" -o O.dat`
the result was:
![Graph1](https://user-images.githubusercontent.com/45874475/105029356-3752e480-5a8d-11eb-89ff-c9de012032e3.jpg)
which is much more resonable in terms of experimental findings and other computational results.
@fxcoudert

**Comment by fxcoudert** [comment]
Hi @Luthaf, we think there is a problem in the unwrap part of the MSD calculation if the system cell size is not constant. The trajectory was obtained during NPT simulation, and it is at a temperature below melting, so it shows very little diffusion (and only the Na species is moving). We have checked this visually, as well as with a “fake” MSD calculation pretending we have a fixed unit cell size equal to the average cell size (second graph on @like611's report).

But when we try to calculate the MSD with variable cell, using unwrap, the result is the first graph: the behaviour of the curve is not physical and does not match the reality of the small atomic movements/vibrations observed.

We're willing to debug this further, but I am not sure how. Do you have an idea?

**Comment by Luthaf** [comment]
Thanks for taking the time to open this issue!

Reading the unwrap algorithm again, I'm not sure how it works anymore ...

https://github.com/chemfiles/cfiles/blob/70882e616f4f06986360d331d9f967c0993d011c/src/commands/Msd.cpp#L201-L211

`current_positions` is the current frame *wrapped* positions, `previous_positions` is the previous frame *wrapped* positions and `position` should contain the unwrapped positions. I'll have a deeper look using your trajectory.

**Comment by Luthaf** [comment]
So I can not reproduce the issue here: using the trajectory in the initial comment, a fresh build of cfiles and the following commands:

```
./cfiles msd 1000K-NPT-200ps.gro --unwrap --selection "name O" -o O.dat
./cfiles msd 1000K-NPT-200ps.gro --unwrap --selection "name Si" -o Si.dat
./cfiles msd 1000K-NPT-200ps.gro --unwrap --selection "name Na" -o Na.dat
```

I get this graph, which looks fine:
![msd](https://user-images.githubusercontent.com/6141587/105058500-91947b00-5a76-11eb-8aa1-3ba79b75133a.png)

Could you double check that you are seeing the issue with a clean build of cfiles? If you do, can you share more information on your system? Operating system and compiler in particular.

**Comment by like611** [comment]
Thanks for your reply.
I recalculated the MSDs using the code:
` cfiles msd 1000K-NPT-200ps.gro --unwrap --selection "name O" -o O.dat`
I still got the resuts the same as the Graph 1. The operating system is GNU/Linux and the compiler is GCC:(GNU) 4.8.5
![image](https://user-images.githubusercontent.com/45874475/105131563-230df680-5b24-11eb-9e72-5f76db09d54e.png)

**Comment by fxcoudert** [comment]
@like611 I compiled the latest version of cfiles on my mac, and it gives me the same as @Luthaf.
Can you tell me what you get for `cfiles --version`?

**Comment by like611** [comment]
My version is not the latest version, the output version of cfiles was:
`cfiles version 0.1.0-52e0d87 (using chemfiles 0.9.0)`

**Comment by fxcoudert** [comment]
@like611 you need to recompile from the latest source. Do you need help with that?

**Comment by like611** [comment]
I just recompiled it with the help of @Luthaf  and then the results were the same as yours. Thanks a lot for your help @fxcoudert @Luthaf !
