### ISSUE TITLE
admin rights

### ISSUE THREAD

**Issue by maxlevesque** [chemfiles/cfiles#7]
One needs rights to write to /usr/local/bin/cfiles.

``` bash
CMake Error at cmake_install.cmake:42 (file):
  file INSTALL cannot copy file
  "/home/X/XX/cfiles/build/cfiles"
  to "/usr/local/bin/cfiles".
```

Don't you think it is not desirable for this kind of tool?

**Comment by Luthaf** [comment]
Sorry, cfiles lacks a bit of documentation ... You can use the `-DCMAKE_INSTALL_PREFIX=<...>` flag to cmake in order to use another installation prefix. So the build look like that:

``` sh
mkdir build
cd build 
cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..  # or anything else
make install
```

I should definitively add a getting started guide.

**Comment by maxlevesque** [comment]
I forked and added your suggestion to your doc, but at the end you may prefer the /usr/local/bin option so I did not do any pull request. Thanks for your answer :)

**Comment by Luthaf** [comment]
I updated the readme to remove make install. This is no longer needed since https://github.com/chemfiles/chemfiles/commit/065c4b6e5ca36a1c6203cd20634d7da6b1d1ea90 and https://github.com/chemfiles/chemfiles/commit/3b112e70b81bdfc5d1225453e3b6e584ed5fb1df.
